Fix compile error on OS X introduced by commit ecf778bbec2794562bf5e5b8645e2171f7cd081c
The following error occurs on OS X with the order reversed: `MCServer/src/World.cpp:282:2: error: field 'm_LastSave' will be initialized after field 'm_LastUnload' [-Werror,-Wreorder] m_LastSave(0),`.    Reversing the order of initialization fixes this.